theme: jekyll-theme-midnight
<html>
  <head>
    <title>Ollie Lueck, Data Analyst and Entrepreneur</title>
  </head>
  <body>
    <p>I am a senior at Denison University with a major in Data Analytics and a minor in Economics. As a data scientist with a liberal arts background, I have a passion for numbers and a curiosity about the world around me. I am interested in investigating topics not necessarily known for being quantifable. Do you have a position that requires some out of the box thinking and creative data analysis? Then you've found the right person!</p>
  </body>
</html>
